
export const topLocationsInMumbai = [
    { name: "Andheri" },
    { name: "Bandra" },
    { name: "Borivali" },
    { name: "Chembur" },
    { name: "Churchgate" },
    { name: "Colaba" },
    { name: "Dadar" },
    { name: "Goregaon" },
    { name: "Juhu Beach" },
    { name: "Kurla" },
    { name: "Lower Parel" },
    { name: "Malad" },
    { name: "Marine Drive" },
    { name: "Mulund" },
    { name: "Powai" },
    { name: "Santacruz" },
    { name: "Thane" },
    { name: "Versova" },
    { name: "Vile Parle" },
    { name: "Worli" }
  ];
  

export const topCollegesInMumbai = [
  { name: "Amity University" },
  { name: "Bhavan's College" },
  { name: "Bharati Vidyapeeth Institute of Management and Research" },
  { name: "Chetana's Institute of Management and Research" },
  { name: "DG Ruparel College" },
  { name: "Elphinstone College" },
  { name: "Guru Nanak College of Arts, Science and Commerce" },
  { name: "Hinduja College of Commerce" },
  { name: "HR College of Commerce and Economics" },
  { name: "IES Management College and Research Centre" },
  { name: "Institute of Chemical Technology (ICT)" },
  { name: "Jai Hind College" },
  { name: "KC College" },
  { name: "KJ Somaiya College of Arts and Commerce" },
  { name: "LS Raheja College of Arts and Commerce" },
  { name: "Lokmanya Tilak College of Engineering" },
  { name: "Mahatma Gandhi Mission College of Engineering and Technology" },
  { name: "Mithibai College" },
  { name: "MET Institute of Management" },
  { name: "Narsee Monjee College of Commerce and Economics" },
  { name: "National College" },
  { name: "National Institute of Fashion Technology (NIFT)" },
  { name: "National Institute of Industrial Engineering (NITIE)" },
  { name: "NMIMS (Deemed University)" },
  { name: "Pillai College of Arts, Commerce, and Science" },
  { name: "Ramnarain Ruia Autonomous College" },
  { name: "Rizvi College of Arts, Science and Commerce" },
  { name: "Rizvi College of Engineering" },
  { name: "R. A. Podar College of Commerce and Economics" },
  { name: "S K Somaiya College" },
  { name: "Sardar Patel Institute of Technology" },
  { name: "SIES College of Arts, Science and Commerce" },
  { name: "SNDT Women's University" },
  { name: "Sophia College for Women" },
  { name: "SP Jain Institute of Management and Research" },
  { name: "St. Andrew’s College" },
  { name: "St. Xavier's College" },
  { name: "Swami Vivekanand College" },
  { name: "Sydenham College of Commerce and Economics" },
  { name: "Thadomal Shahani Engineering College" },
  { name: "Thakur College of Engineering and Technology" },
  { name: "Tolani College of Commerce" },
  { name: "VES College of Arts, Science and Commerce" },
  { name: "V.G. Vaze College of Arts, Science and Commerce" },
  { name: "Vivekanand Education Society's Institute of Technology" },
  { name: "Wilson College" },
  { name: "Welingkar Institute of Management Development & Research" },
  { name: "Xavier Institute of Engineering" },
  { name: "Sasmira's Institute of Management Studies and Research" },
  { name: "Mumbai University (Kalina Campus)" },
  { name: "Rajiv Gandhi Institute of Technology" },
];

export const studentBudgetForFlats = [
  { range: "Below ₹5,000" },
  { range: "₹5,000 - ₹10,000" },
  { range: "₹10,000 - ₹15,000" },
  { range: "₹15,000 - ₹20,000" },
  { range: "₹20,000 - ₹25,000" },
];


export const flatmatePreferences = [
    { preference: "Non-smoker" },
    { preference: "Vegetarian" },
    { preference: "Vegan" },
    { preference: "Quiet and Studious" },
    { preference: "Clean and Organized" },
    { preference: "No late-night parties" },
    { preference: "Pet-friendly" },
    { preference: "Shares household chores" },
    { preference: "Non-drinker" },
    { preference: "Early riser" },
    { preference: "Night owl" },
    { preference: "Works from home" },
    { preference: "Respectful of personal space" },
    { preference: "Environmentally conscious" },
    { preference: "Minimalist" },
    { preference: "Fitness enthusiast" },
    { preference: "Tech-savvy" },
    { preference: "Social and outgoing" },
    { preference: "Introverted" },
    { preference: "Frequent traveler" },
    { preference: "Musician or Artist" },
    { preference: "Spiritual or Religious" },
    { preference: "Open to cooking together" },
    { preference: "Prefer privacy" },
    { preference: "Sports enthusiast" },
    { preference: "Book lover" },
    { preference: "Board games or video games lover" },
    { preference: "Creative or artistic" },
    { preference: "Prefers minimal guests" },
    { preference: "Involved in social causes" },
    { preference: "Flexible with sleep schedules" },
    { preference: "Enjoys outdoor activities" },
    { preference: "Prefers a calm environment" },
    { preference: "LGBTQ+ friendly" },
    { preference: "Enjoys watching movies or TV shows together" },
    { preference: "Talkative and friendly" },
    { preference: "Prefers quiet time" },
    { preference: "Open to sharing groceries" },
    { preference: "Eco-friendly lifestyle" },
    { preference: "Interested in healthy living" },
    { preference: "Freelancer or part-time worker" },
    { preference: "Flexible with shared spaces" },
    { preference: "Mindful of electricity and water usage" },
    { preference: "Allergic to pets" },
    { preference: "Enjoys group activities" },
    { preference: "Prefers to keep to themselves" }
  ];

  

export const studentSelfDescription = [
    { description: "Non-smoker" },
    { description: "Vegetarian" },
    { description: "Vegan" },
    { description: "Quiet and studious" },
    { description: "Clean and organized" },
    { description: "Social and outgoing" },
    { description: "Introverted" },
    { description: "Fitness enthusiast" },
    { description: "Creative or artistic" },
    { description: "Tech-savvy" },
    { description: "Adventurous" },
    { description: "Open-minded" },
    { description: "Pet lover" },
    { description: "Book lover" },
    { description: "Frequent traveler" },
    { description: "Musician or artist" },
    { description: "Spiritual or religious" },
    { description: "Hardworking" },
    { description: "Goal-oriented" },
    { description: "Friendly and approachable" },
    { description: "Detail-oriented" },
    { description: "Flexible with living arrangements" },
    { description: "Mindful of personal space" },
    { description: "Enjoys cooking" },
    { description: "Enjoys outdoor activities" },
    { description: "Loves to host gatherings" },
    { description: "Frequent gamer" },
    { description: "Passionate about social causes" },
    { description: "Fluent in multiple languages" },
    { description: "Dancer or performer" },
    { description: "Enjoys watching movies and series" },
    { description: "Environmental activist" },
    { description: "Interested in healthy living" },
    { description: "Open to making new friends" },
    { description: "Prefers a calm environment" },
    { description: "Good listener" },
    { description: "Enjoys board games" },
    { description: "Punctual and responsible" },
    { description: "Ambitious" },
    { description: "Likes to volunteer" },
    { description: "Curious and inquisitive" },
    { description: "Enjoys team activities" },
    { description: "Crafty or DIY enthusiast" },
    { description: "Loves pets" },
    { description: "Culturally aware" },
    { description: "Foodie" },
    { description: "Enjoys gardening" },
    { description: "Enthusiastic about learning" },
    { description: "Detail-oriented" },
    { description: "Public speaker" },
    { description: "Enjoys art and culture" },
    { description: "Friendly towards everyone" },
    { description: "Believes in work-life balance" },
    { description: "Participates in student clubs" },
    { description: "Seeks to grow personally and professionally" },
    { description: "Has a strong sense of community" },
    { description: "Enjoys attending workshops" },
    { description: "Interested in technology trends" },
    { description: "Loves nature and the outdoors" },
    { description: "Active in sports" },
    { description: "Enjoys baking" },
    { description: "Involved in student government" },
    { description: "Loves history" },
    { description: "Appreciates diverse cultures" },
    { description: "Enjoys public transportation" },
    { description: "Advocate for mental health awareness" }
  ];
  