
export const topLocationsInMumbai = [
  { label: "Andheri", value: "andheri" },
  { label: "Bandra", value: "bandra" },
  { label: "Borivali", value: "borivali" },
  { label: "Chembur", value: "chembur" },
  { label: "Churchgate", value: "churchgate" },
  { label: "Colaba", value: "colaba" },
  { label: "Dadar", value: "dadar" },
  { label: "Goregaon", value: "goregaon" },
  { label: "Juhu Beach", value: "juhu_beach" },
  { label: "Kurla", value: "kurla" },
  { label: "Lower Parel", value: "lower_parel" },
  { label: "Malad", value: "malad" },
  { label: "Marine Drive", value: "marine_drive" },
  { label: "Mulund", value: "mulund" },
  { label: "Powai", value: "powai" },
  { label: "Santacruz", value: "santacruz" },
  { label: "Thane", value: "thane" },
  { label: "Versova", value: "versova" },
  { label: "Vile Parle", value: "vile_parle" },
  { label: "Worli", value: "worli" }
];
  

// colleges.js
export const topCollegesInMumbai = [
  { label: "Amity University", value: "amity_university" },
  { label: "Bhavan's College", value: "bhavans_college" },
  { label: "Bharati Vidyapeeth Institute of Management and Research", value: "bharati_vidyapeeth_institute_of_management_and_research" },
  { label: "Chetana's Institute of Management and Research", value: "chetanas_institute_of_management_and_research" },
  { label: "DG Ruparel College", value: "dg_ruparel_college" },
  { label: "Elphinstone College", value: "elphinstone_college" },
  { label: "Guru Nanak College of Arts, Science and Commerce", value: "guru_nanak_college_of_arts_science_and_commerce" },
  { label: "Hinduja College of Commerce", value: "hinduja_college_of_commerce" },
  { label: "HR College of Commerce and Economics", value: "hr_college_of_commerce_and_economics" },
  { label: "IES Management College and Research Centre", value: "ies_management_college_and_research_centre" },
  { label: "Institute of Chemical Technology (ICT)", value: "ict" },
  { label: "Jai Hind College", value: "jai_hind_college" },
  { label: "KC College", value: "kc_college" },
  { label: "KJ Somaiya College of Arts and Commerce", value: "kj_somaiya_college_of_arts_and_commerce" },
  { label: "LS Raheja College of Arts and Commerce", value: "ls_raheja_college_of_arts_and_commerce" },
  { label: "Lokmanya Tilak College of Engineering", value: "lokmanya_tilak_college_of_engineering" },
  { label: "Mahatma Gandhi Mission College of Engineering and Technology", value: "mahatma_gandhi_mission_college_of_engineering_and_technology" },
  { label: "Mithibai College", value: "mithibai_college" },
  { label: "MET Institute of Management", value: "met_institute_of_management" },
  { label: "Narsee Monjee College of Commerce and Economics", value: "narsee_monjee_college_of_commerce_and_economics" },
  { label: "National College", value: "national_college" },
  { label: "National Institute of Fashion Technology (NIFT)", value: "nift" },
  { label: "National Institute of Industrial Engineering (NITIE)", value: "nitie" },
  { label: "NMIMS (Deemed University)", value: "nmims" },
  { label: "Pillai College of Arts, Commerce, and Science", value: "pillai_college_of_arts_commerce_and_science" },
  { label: "Ramnarain Ruia Autonomous College", value: "ramnarain_ruia_autonomous_college" },
  { label: "Rizvi College of Arts, Science and Commerce", value: "rizvi_college_of_arts_science_and_commerce" },
  { label: "Rizvi College of Engineering", value: "rizvi_college_of_engineering" },
  { label: "R. A. Podar College of Commerce and Economics", value: "ra_podar_college_of_commerce_and_economics" },
  { label: "S K Somaiya College", value: "sk_somaiya_college" },
  { label: "Sardar Patel Institute of Technology", value: "sardar_patel_institute_of_technology" },
  { label: "SIES College of Arts, Science and Commerce", value: "sies_college_of_arts_science_and_commerce" },
  { label: "SNDT Women's University", value: "sndt_womens_university" },
  { label: "Sophia College for Women", value: "sophia_college_for_women" },
  { label: "SP Jain Institute of Management and Research", value: "sp_jain_institute_of_management_and_research" },
  { label: "St. Andrew’s College", value: "st_andrews_college" },
  { label: "St. Xavier's College", value: "st_xaviers_college" },
  { label: "Swami Vivekanand College", value: "swami_vivekanand_college" },
  { label: "Sydenham College of Commerce and Economics", value: "sydenham_college_of_commerce_and_economics" },
  { label: "Thadomal Shahani Engineering College", value: "thadomal_shahani_engineering_college" },
  { label: "Thakur College of Engineering and Technology", value: "thakur_college_of_engineering_and_technology" },
  { label: "Tolani College of Commerce", value: "tolani_college_of_commerce" },
  { label: "VES College of Arts, Science and Commerce", value: "ves_college_of_arts_science_and_commerce" },
  { label: "V.G. Vaze College of Arts, Science and Commerce", value: "vg_vaze_college_of_arts_science_and_commerce" },
  { label: "Vivekanand Education Society's Institute of Technology", value: "vivekanand_education_society_institute_of_technology" },
  { label: "Wilson College", value: "wilson_college" },
  { label: "Welingkar Institute of Management Development & Research", value: "welingkar_institute_of_management" },
  { label: "Xavier Institute of Engineering", value: "xavier_institute_of_engineering" },
  { label: "Sasmira's Institute of Management Studies and Research", value: "sasmira_institute_of_management_studies_and_research" },
  { label: "Mumbai University (Kalina Campus)", value: "mumbai_university_kalina_campus" },
  { label: "Rajiv Gandhi Institute of Technology", value: "rajiv_gandhi_institute_of_technology" }
];

export const studentBudgetForFlats = [
  { value: "below_5000", label: "Below ₹5,000" },
  { value: "5000_10000", label: "₹5,000 - ₹10,000" },
  { value: "10000_15000", label: "₹10,000 - ₹15,000" },
  { value: "15000_20000", label: "₹15,000 - ₹20,000" },
  { value: "20000_25000", label: "₹20,000 - ₹25,000" },
  { value: "above_25000", label: "Above ₹25,000" },
];

// preferences.js
export const flatmatePreferences = [
  { label: "Non-smoker", value: "non_smoker" },
  { label: "Vegetarian", value: "vegetarian" },
  { label: "Vegan", value: "vegan" },
  { label: "Quiet and Studious", value: "quiet_and_studious" },
  { label: "Clean and Organized", value: "clean_and_organized" },
  { label: "No late-night parties", value: "no_late_night_parties" },
  { label: "Pet-friendly", value: "pet_friendly" },
  { label: "Shares household chores", value: "shares_household_chores" },
  { label: "Non-drinker", value: "non_drinker" },
  { label: "Early riser", value: "early_riser" },
  { label: "Night owl", value: "night_owl" },
  { label: "Works from home", value: "works_from_home" },
  { label: "Respectful of personal space", value: "respectful_of_personal_space" },
  { label: "Environmentally conscious", value: "environmentally_conscious" },
  { label: "Minimalist", value: "minimalist" },
  { label: "Fitness enthusiast", value: "fitness_enthusiast" },
  { label: "Tech-savvy", value: "tech_savvy" },
  { label: "Social and outgoing", value: "social_and_outgoing" },
  { label: "Introverted", value: "introverted" },
  { label: "Frequent traveler", value: "frequent_traveler" },
  { label: "Musician or Artist", value: "musician_or_artist" },
  { label: "Spiritual or Religious", value: "spiritual_or_religious" },
  { label: "Open to cooking together", value: "open_to_cooking_together" },
  { label: "Prefer privacy", value: "prefer_privacy" },
  { label: "Sports enthusiast", value: "sports_enthusiast" },
  { label: "Book lover", value: "book_lover" },
  { label: "Board games or video games lover", value: "board_games_or_video_games_lover" },
  { label: "Creative or artistic", value: "creative_or_artistic" },
  { label: "Prefers minimal guests", value: "prefers_minimal_guests" },
  { label: "Involved in social causes", value: "involved_in_social_causes" },
  { label: "Flexible with sleep schedules", value: "flexible_with_sleep_schedules" },
  { label: "Enjoys outdoor activities", value: "enjoys_outdoor_activities" },
  { label: "Prefers a calm environment", value: "prefers_a_calm_environment" },
  { label: "LGBTQ+ friendly", value: "lgbtq_friendly" },
  { label: "Enjoys watching movies or TV shows together", value: "enjoys_watching_movies_or_tv_shows_together" },
  { label: "Talkative and friendly", value: "talkative_and_friendly" },
  { label: "Prefers quiet time", value: "prefers_quiet_time" },
  { label: "Open to sharing groceries", value: "open_to_sharing_groceries" },
  { label: "Eco-friendly lifestyle", value: "eco_friendly_lifestyle" },
  { label: "Interested in healthy living", value: "interested_in_healthy_living" },
  { label: "Freelancer or part-time worker", value: "freelancer_or_part_time_worker" },
  { label: "Flexible with shared spaces", value: "flexible_with_shared_spaces" },
  { label: "Mindful of electricity and water usage", value: "mindful_of_electricity_and_water_usage" },
  { label: "Allergic to pets", value: "allergic_to_pets" },
  { label: "Enjoys group activities", value: "enjoys_group_activities" },
  { label: "Prefers to keep to themselves", value: "prefers_to_keep_to_themselves" }
];

  


  